version: "2.4"
services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres:/var/lib/postgresql/data
