// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package queries

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type SamlFlowStepType string

const (
	SamlFlowStepTypeGetRedirect          SamlFlowStepType = "get_redirect"
	SamlFlowStepTypeSamlInitiate         SamlFlowStepType = "saml_initiate"
	SamlFlowStepTypeSamlReceiveAssertion SamlFlowStepType = "saml_receive_assertion"
	SamlFlowStepTypeRedeem               SamlFlowStepType = "redeem"
)

func (e *SamlFlowStepType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SamlFlowStepType(s)
	case string:
		*e = SamlFlowStepType(s)
	default:
		return fmt.Errorf("unsupported scan type for SamlFlowStepType: %T", src)
	}
	return nil
}

type NullSamlFlowStepType struct {
	SamlFlowStepType SamlFlowStepType
	Valid            bool // Valid is true if SamlFlowStepType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSamlFlowStepType) Scan(value interface{}) error {
	if value == nil {
		ns.SamlFlowStepType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SamlFlowStepType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSamlFlowStepType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SamlFlowStepType), nil
}

type ApiKey struct {
	ID                uuid.UUID
	AppOrganizationID uuid.UUID
	SecretValue       string
}

type AppOrganization struct {
	ID                 uuid.UUID
	GoogleHostedDomain *string
}

type AppSession struct {
	ID         uuid.UUID
	AppUserID  uuid.UUID
	CreateTime time.Time
	ExpireTime time.Time
	Token      string
}

type AppUser struct {
	ID                uuid.UUID
	AppOrganizationID uuid.UUID
	DisplayName       string
	Email             *string
}

type Environment struct {
	ID                uuid.UUID
	RedirectUrl       *string
	AppOrganizationID uuid.UUID
	DisplayName       *string
	AuthUrl           *string
}

type Organization struct {
	ID            uuid.UUID
	EnvironmentID uuid.UUID
	ExternalID    *string
}

type OrganizationDomain struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Domain         string
}

type SamlConnection struct {
	ID                 uuid.UUID
	OrganizationID     uuid.UUID
	IdpRedirectUrl     *string
	IdpX509Certificate []byte
	IdpEntityID        *string
	SpEntityID         *string
}

type SamlFlow struct {
	ID                   uuid.UUID
	SamlConnectionID     uuid.UUID
	AccessCode           uuid.UUID
	State                string
	CreateTime           time.Time
	ExpireTime           time.Time
	SubjectIdpID         *string
	SubjectIdpAttributes []byte
}

type SamlFlowStep struct {
	ID                          uuid.UUID
	SamlFlowID                  uuid.UUID
	Timestamp                   time.Time
	Type                        SamlFlowStepType
	GetRedirectUrl              *string
	SamlInitiateUrl             *string
	SamlReceiveAssertionPayload *string
}

type SchemaMigration struct {
	Version int64
	Dirty   bool
}
