// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package queries

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type SamlLoginEventTimelineEntryType string

const (
	SamlLoginEventTimelineEntryTypeGetRedirect          SamlLoginEventTimelineEntryType = "get_redirect"
	SamlLoginEventTimelineEntryTypeSamlInitiate         SamlLoginEventTimelineEntryType = "saml_initiate"
	SamlLoginEventTimelineEntryTypeSamlReceiveAssertion SamlLoginEventTimelineEntryType = "saml_receive_assertion"
	SamlLoginEventTimelineEntryTypeRedeem               SamlLoginEventTimelineEntryType = "redeem"
)

func (e *SamlLoginEventTimelineEntryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SamlLoginEventTimelineEntryType(s)
	case string:
		*e = SamlLoginEventTimelineEntryType(s)
	default:
		return fmt.Errorf("unsupported scan type for SamlLoginEventTimelineEntryType: %T", src)
	}
	return nil
}

type NullSamlLoginEventTimelineEntryType struct {
	SamlLoginEventTimelineEntryType SamlLoginEventTimelineEntryType
	Valid                           bool // Valid is true if SamlLoginEventTimelineEntryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSamlLoginEventTimelineEntryType) Scan(value interface{}) error {
	if value == nil {
		ns.SamlLoginEventTimelineEntryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SamlLoginEventTimelineEntryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSamlLoginEventTimelineEntryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SamlLoginEventTimelineEntryType), nil
}

type ApiKey struct {
	ID                uuid.UUID
	AppOrganizationID uuid.UUID
	SecretValue       string
}

type AppOrganization struct {
	ID                 uuid.UUID
	GoogleHostedDomain *string
}

type AppSession struct {
	ID         uuid.UUID
	AppUserID  uuid.UUID
	CreateTime time.Time
	ExpireTime time.Time
	Token      string
}

type AppUser struct {
	ID                uuid.UUID
	AppOrganizationID uuid.UUID
	DisplayName       string
	Email             *string
}

type Environment struct {
	ID                uuid.UUID
	RedirectUrl       *string
	AppOrganizationID uuid.UUID
	DisplayName       *string
	AuthUrl           *string
}

type Organization struct {
	ID            uuid.UUID
	EnvironmentID uuid.UUID
	ExternalID    *string
}

type OrganizationDomain struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Domain         string
}

type SamlConnection struct {
	ID                 uuid.UUID
	OrganizationID     uuid.UUID
	IdpRedirectUrl     *string
	IdpX509Certificate []byte
	IdpEntityID        *string
	SpEntityID         *string
}

type SamlLoginEvent struct {
	ID                   uuid.UUID
	SamlConnectionID     uuid.UUID
	AccessCode           uuid.UUID
	State                string
	ExpireTime           time.Time
	SubjectIdpID         *string
	SubjectIdpAttributes []byte
}

type SamlLoginEventTimelineEntry struct {
	ID                          uuid.UUID
	SamlLoginEventID            uuid.UUID
	Timestamp                   time.Time
	Type                        SamlLoginEventTimelineEntryType
	GetRedirectUrl              *string
	SamlInitiateUrl             *string
	SamlReceiveAssertionPayload *string
}

type SamlSession struct {
	ID                   uuid.UUID
	SamlConnectionID     uuid.UUID
	SecretAccessToken    *uuid.UUID
	SubjectID            *string
	SubjectIdpAttributes []byte
}

type SchemaMigration struct {
	Version int64
	Dirty   bool
}
