# fly.toml app configuration file generated for ssoready-admin-custom-domain on 2024-09-09T13:47:28-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ssoready-admin-custom-domain'
primary_region = 'iad'

[build]

[env]
  AUTHPROXY_AUTH_URL = 'https://admin.ssoready.com'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 3
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
