# fly.toml app configuration file generated for adminproxy-ember-cloud-9275 on 2024-09-09T11:42:34-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'adminproxy-ember-cloud-9275'
primary_region = 'iad'

[build]

[env]
  AUTHPROXY_AUTH_URL = 'https://stage--ssoready-admin.netlify.app'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
