app = 'ssoready-auth-custom-domain'
primary_region = 'iad'

[build]

[env]
  AUTHPROXY_AUTH_URL = 'https://admin.ssoready.com'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
